//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_iLB_Host_ChoiceListsToArray

// Compiler method for the iLB_Host_ChoiceListsToArray method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by iLB on Jun 29, 2010.
// ----------------------------------------------------

C_POINTER:C301(iLB_Host_ChoiceListsToArray; $1)
C_POINTER:C301(iLB_Host_ChoiceListsToArray; $2)
