//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_SaveList

// Compiler method for the Fnd_Host_SaveList method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Feb 3, 2011.
// ----------------------------------------------------

C_TEXT:C284(Fnd_Host_SaveList; $1)
C_BLOB:C604(Fnd_Host_SaveList; $2)
