//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_IO_DisplayDia

// Compiler method for the Fnd_Host_IO_DisplayDialog method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Jun 24, 2010.
// ----------------------------------------------------

C_TEXT:C284(Fnd_Host_IO_DisplayDialog; $1)
