//%attributes = {"invisible":true,"executedOnServer":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_Tlbr_ButtonCl

// Compiler method for the Fnd_Host_Tlbr_ButtonClck method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Mar 1, 2010.
// ----------------------------------------------------

C_POINTER:C301(Fnd_Host_Tlbr_ButtonClck; $1)
