//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_Tlbr_SetBtnPi

// Compiler method for the Fnd_Host_Tlbr_SetBtnPict method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Sep 30, 2009.
// ----------------------------------------------------

C_LONGINT:C283(Fnd_Host_Tlbr_SetBtnPict; $1)
C_PICTURE:C286(Fnd_Host_Tlbr_SetBtnPict; $2)
