//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_GetFormProp

// Compiler method for the Fnd_Host_GetFormProperties method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Sep 30, 2009.
// ----------------------------------------------------

C_POINTER:C301(Fnd_Host_GetFormProperties; $1; $3; $4)
C_TEXT:C284(Fnd_Host_GetFormProperties; $2)
