//%attributes = {"invisible":true}
// ----------------------------------------------------
// Project Method: Compiler_Fnd_Host_Tlbr_SetMessa

// Compiler method for the Fnd_Host_Tlbr_SetMessage method.

// Access: Private

// Parameters: None

// Returns: Nothing

// This method was automatically generated by Foundation on Sep 30, 2009.
// ----------------------------------------------------

C_TEXT:C284(Fnd_Host_Tlbr_SetMessage; $1)
