//%attributes = {"shared":true}
// ----------------------------------------------------
// Project Method: Fnd_Hook_IO_SelectionChanged

// Go to Product Sales example database to copy the example for this method
// This method was automatically generated by Foundation 5 on May 7, 2009.
// ----------------------------------------------------

UNLOAD RECORD:C212(Fnd_Gen_CurrentTable->)

