//%attributes = {"shared":true}
// ----------------------------------------------------
// Project Method: iLB_Hook_TableBrowser2

//<-parameterblock-> 
// Go to the example database to copy the example for this method
// This method was automatically generated by iLB on Jun 29, 2010.
// iLB is Copyright 2009 - 2010-- IBB Consulting, LLC 
// ----------------------------------------------------

C_LONGINT:C283($1; $iTable)
C_LONGINT:C283($2; $iView)

$iTable:=$1
$iView:=$2

$0:=1

