//%attributes = {"shared":true}
// ----------------------------------------------------
// Project Method: iLB_Hook_OutputFormMethod

//<-parameterblock-> 
// Go to the example database to copy the example for this method
// This method was automatically generated by iLB on Jun 29, 2010.
// iLB is Copyright 2009 - 2010-- IBB Consulting, LLC 
// ----------------------------------------------------

C_POINTER:C301($1; $ptrObject)
C_LONGINT:C283($0)

$ptrObject:=$1

$0:=1

